version: "3.9"

services:
  mlflow-ui:
    build: .
    command: >
      sh -c "mlflow ui --host 0.0.0.0 --port 5000
             --backend-store-uri ${MLFLOW_TRACKING_URI}"
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./mlruns:/workspace/mlruns
      - ./data:/workspace/data

  api:
    build: .
    command: >
      sh -c "python -m uvicorn app.app:app --host 0.0.0.0 --port ${PORT}"
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    volumes:
      - ./mlruns:/workspace/mlruns
      - ./data:/workspace/data
    depends_on:
      - mlflow-ui

  trainer:
    build: .
    command: >
      sh -c "python training/train_model.py"
    env_file:
      - .env
    volumes:
      - ./mlruns:/workspace/mlruns
      - ./data:/workspace/data
      - ./training:/workspace/training   # 👈 mount training code
      - ./artifacts:/workspace/artifacts   # 👈 mount artifacts folder
    depends_on:
      - mlflow-ui

  promote:
    build: .
    command: >
      sh -c "python ci/promote_if_better.py"
    env_file:
      - .env
    volumes:
      - ./mlruns:/workspace/mlruns
      - ./data:/workspace/data
    depends_on:
      - mlflow-ui
