name: Fraud Detection MLOps

on:
  schedule:
    - cron: "0 0 1 * *"   # retrain on the 1st of each month
  workflow_dispatch:       # allow manual trigger for testing

jobs:
  train-promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training
        run: python training/train_model.py

      - name: Promote model
        run: python ci/promote_if_better.py
