name: Fraud Detection MLOps

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  train-promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Prepare environment file
        run: |
          if [ ! -f .env ]; then
            cp .env.example .env
          fi

      - name: Prepare mlruns folder
        run: mkdir -p mlruns && chmod -R 777 mlruns

      - name: Build containers
        run: docker compose build

      - name: Run training
        run: docker compose run --rm trainer

      - name: Run promotion
        run: docker compose run --rm promote
