name: Fraud Detection MLOps

on:
  schedule:
    - cron: "0 0 1 * *"   # retrain on the 1st of each month
  workflow_dispatch:       # allow manual trigger for testing

jobs:
  train-promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # .env file exists for docker-compose
      - name: Prepare environment file
        run: |
          if [ ! -f .env ]; then
            echo "Using .env.example as fallback"
            cp .env.example .env
          fi
          cat .env

      - name: Build containers
        run: docker compose build

      - name: Run training
        run: docker compose run --rm trainer

      - name: Run promotion
        run: docker compose run --rm promote
