name: Fraud Detection MLOps

on:
  schedule:
    - cron: "0 0 1 * *"   # retrain on the 1st of each month
  workflow_dispatch:       # allow manual trigger for testing

jobs:
  train-promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Ensure .env exists (fallback to .env.example if missing)
      - name: Prepare environment file
        run: |
          if [ ! -f .env ]; then
            echo "No .env found, copying from .env.example"
            cp .env.example .env
          fi
          cat .env

      # Make sure mlruns, data, and artifacts directories exist & are writable
      - name: Prepare folders
        run: |
          mkdir -p mlruns && chmod -R 777 mlruns
          mkdir -p data && chmod -R 777 data
          mkdir -p artifacts && chmod -R 777 artifacts

      - name: Build containers
        run: docker compose build

      # Initialize the SQLite database from CSV
      - name: Initialize fraud.db
        run: docker compose run --rm trainer python data/init_db.py

      - name: Run training
        run: docker compose run --rm trainer

      - name: Run promotion
        run: docker compose run --rm promote

      - name: Upload training artifacts (mlruns + plots + DB)
        uses: actions/upload-artifact@v4
        with:
          name: training-artifacts
          path: |
            mlruns/
            artifacts/
            data/fraud.db

  deploy-local:
    runs-on: self-hosted   # 👈 must run on your local runner
    needs: train-promote   # waits until training+promotion finished
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download training artifacts
        uses: actions/download-artifact@v4
        with:
          name: training-artifacts
          path: ./_ci_download

      - name: Replace local mlruns with promoted registry
        run: |
          mkdir -p mlruns
          rm -rf mlruns/*
          cp -r _ci_download/mlruns/* mlruns/
          chmod -R 777 mlruns

      - name: Restart API to load latest Production model
        run: docker compose restart api

      - name: (Optional) Show API health
        run: curl -s http://localhost:${PORT:-8000}/docs >/dev/null && echo "API is up"
