name: Fraud Detection MLOps

on:
  schedule:
    - cron: "0 0 1 * *"   # retrain on the 1st of each month
  workflow_dispatch:       # allow manual trigger for testing

jobs:
  train-promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Ensure .env exists (fallback to .env.example if missing)
      - name: Prepare environment file
        run: |
          if [ ! -f .env ]; then
            echo "No .env found, copying from .env.example"
            cp .env.example .env
          fi
          cat .env

      # Make sure mlruns and data directories exist & are writable
      - name: Prepare folders
        run: |
          mkdir -p mlruns && chmod -R 777 mlruns
          mkdir -p data && chmod -R 777 data
          mkdir -p artifacts && chmod -R 777 artifacts

      - name: Build containers
        run: docker compose build

      # Initialize the SQLite database from CSV
      - name: Initialize fraud.db
        run: docker compose run --rm trainer python data/init_db.py

      - name: Run training
        run: docker compose run --rm trainer

      - name: Run promotion
        run: docker compose run --rm promote
